import type { PgTable } from "./get_schema"
import { RawSQL, type Field, type Table } from "./schema"


const getDefaultValue = (col: Field) => {
  if (col.default instanceof RawSQL) {
    return col.default.sql
  }
  if ((col.type === "integer" || col.type === "bigint") && col.default === "inc") {
    return 'inc'
  }
  if (typeof col.default === 'string') {
    return `'${col.default}'`
  }
  return col.default
}

export const createTable = (table: Table<any>) => {

  const columns = []

  for (let [key, column] of Object.entries<any>(table.schema)) {
    if (typeof column === "string") continue

    columns.push(buildAddColumnClause(table, key, column, ""))
  }

  if (table.primaryKey.length > 1) {
    columns.push(`PRIMARY KEY(${table.primaryKey.map(key => table.schema[key]?.key ?? key).join(",")})`)
  }

  const sql = `
CREATE TABLE ${table.name} (
${columns.join(",\n")}
);
  `

  return sql
}

const normalizeDefault = (val?: string | null | TemplateStringsArray | number): string | undefined => {
  if (val == null) return undefined
  let s = String(val).trim()
  // снять внешние скобки: (now()) -> now()
  if (s.startsWith("(") && s.endsWith(")")) s = s.slice(1, -1)
  // убрать ::type приведение
  s = s.replace(/::[\w\.\[\]\s]+$/, "")
  return s
}

const desiredColName = (key: string, col: any) =>
  "ref" in col ? (col.key as string) : key

const desiredColType = (col: any) => {
  if ("ref" in col && col.ref) {
    const pkKey = col.ref.primaryKey[0]
    const refPk = col.ref.schema[pkKey] as any
    // у ref PK всегда object
    return refPk.type
  }
  return (col.type as string)
}

const buildAddColumnClause = (table: Table<any>, key: string, col: any, prefix = "ADD COLUMN"): string => {
  const name = desiredColName(key, col)
  const type = desiredColType(col)

  const parts: string[] = [prefix, name, type]

  // NOT NULL (кроме случая, когда PK будет задаваться отдельным CONSTRAINT)
    if (col.primaryKey && table.primaryKey.length === 1) {
      parts.push("PRIMARY KEY")
    }
    if (!col.nullable && !parts.includes("PRIMARY KEY")) {
      parts.push("NOT NULL")
    }

  if ("default" in col) {
    if ((col.type === "integer" || col.type === "bigint") && col.default === "inc") {
      parts.push(`GENERATED BY DEFAULT AS IDENTITY`)
    } else {
      parts.push(`DEFAULT ${getDefaultValue(col)}`)
    }
  }

  if (col.unique && !parts.includes("PRIMARY KEY")) {
    parts.push("UNIQUE")
  }

  if ("ref" in col && col.ref) {
    const refTable = col.ref.name
    const refPkKey = col.ref.primaryKey[0]
    parts.push(`REFERENCES ${refTable}(${refPkKey})`)
    if (col.onDelete) parts.push(`ON DELETE ${col.onDelete}`)
    if (col.onUpdate) parts.push(`ON UPDATE ${col.onUpdate}`)
  }

  return parts.join(" ")
}

const pkConstraintName = (tableName: string) => `${tableName}_pkey`
const uniqueConstraintName = (tableName: string, colName: string) => `${tableName}_${colName}_unique`
const fkConstraintName = (tableName: string, colName: string) => `${tableName}_${colName}_fkey`

export function updateTable(pgTable: PgTable, table: Table<any>): string {
  const stmts: string[] = []

  // 1) Добавление отсутствующих колонок
  for (const [key, colDef] of Object.entries(table.schema)) {
    if (typeof colDef === "string") continue // виртуальные поля пропускаем
    const colName = desiredColName(key, colDef)
    if (!pgTable[colName]) {
      stmts.push(`ALTER TABLE ${table.name} ${buildAddColumnClause(table, key, colDef)};`)
    }
  }

  // 2) Модификация существующих колонок (тип, nullability, default, unique, fk)
  for (const [key, colDef] of Object.entries<Field>(table.schema)) {
    if (typeof colDef === "string") continue
    const colName = desiredColName(key, colDef)
    const pgCol = pgTable[colName]
    if (!pgCol) continue // добавили выше

    // 2.1 тип
    const wantType = desiredColType(colDef)
    if (pgCol.type !== wantType) {
      stmts.push(`ALTER TABLE ${table.name} ALTER COLUMN ${colName} TYPE ${wantType};`)
      // сложные изменения типа могут требовать USING — вне scope MVP
    }

    // 2.2 NULL / NOT NULL
    const wantNotNull = !colDef.nullable || colDef.primaryKey

    if (wantNotNull && pgCol.nullable) {
      stmts.push(`ALTER TABLE ${table.name} ALTER COLUMN ${colName} SET NOT NULL;`)
    } else if (!wantNotNull && !pgCol.nullable && !pgCol.primaryKey) {
      stmts.push(`ALTER TABLE ${table.name} ALTER COLUMN ${colName} DROP NOT NULL;`)
    }

    // 2.3 DEFAULT
    const wantDefaultSql = ("default" in colDef) ? getDefaultValue(colDef) : undefined
    const haveDefaultSql = normalizeDefault(pgCol.default)
    const wantDefaultNorm = normalizeDefault(wantDefaultSql)

    if (wantDefaultNorm !== haveDefaultSql) {
      if (wantDefaultSql === undefined) {
        if (haveDefaultSql === "inc") {
          stmts.push(`ALTER TABLE users ALTER COLUMN id DROP IDENTITY;`)
        } else {
          stmts.push(`ALTER TABLE ${table.name} ALTER COLUMN ${colName} DROP DEFAULT;`)
        }
      } else if (wantDefaultNorm === "inc") {
        stmts.push(`ALTER TABLE ${table.name} ALTER COLUMN ${colName} DROP DEFAULT;`)
        stmts.push(`ALTER TABLE ${table.name} ALTER COLUMN ${colName} ADD GENERATED BY DEFAULT AS IDENTITY;`)
      } else {
        stmts.push(`ALTER TABLE ${table.name} ALTER COLUMN ${colName} SET DEFAULT ${getDefaultValue((colDef as any).default)};`)
      }
    }

    // 2.4 UNIQUE (при наличии информации из интроспекции)
    if (typeof pgCol.unique !== "undefined" || typeof colDef.unique !== "undefined") {
      const haveUnique = !!pgCol.unique
      const wantUnique = !!colDef.unique && !(colDef.primaryKey && table.primaryKey.length === 1)

      if (wantUnique && !haveUnique) {
        stmts.push(`ALTER TABLE ${table.name} ADD CONSTRAINT ${uniqueConstraintName(table.name, colName)} UNIQUE (${colName});`)
      } else if (!wantUnique && haveUnique) {
        stmts.push(`ALTER TABLE ${table.name} DROP CONSTRAINT IF EXISTS ${uniqueConstraintName(table.name, colName)};`)
      }
    }

    // 2.5 FOREIGN KEY
    const wantRef = ("ref" in colDef && colDef.ref) ? {
      table: (colDef.ref as any).name as string,
      column: (colDef.ref as any).primaryKey[0] as string,
      onDelete: (colDef as any).onDelete as (string | undefined),
      onUpdate: (colDef as any).onUpdate as (string | undefined),
    } : undefined

    const haveRef = pgCol.references
      ? {
          table: pgCol.references.table,
          column: pgCol.references.column,
          onDelete: pgCol.references.onDelete || undefined,
          onUpdate: pgCol.references.onUpdate || undefined,
          constraintName: pgCol.references.constraintName || fkConstraintName(table.name, colName)
        }
      : undefined


    const refChanged =
      (wantRef && !haveRef) ||
      (!wantRef && !!haveRef) ||
      (wantRef && haveRef &&
        (wantRef.table !== haveRef.table ||
         wantRef.column !== haveRef.column ||
         (wantRef.onDelete || "").toUpperCase() !== (haveRef.onDelete || "").toUpperCase() ||
         (wantRef.onUpdate || "").toUpperCase() !== (haveRef.onUpdate || "").toUpperCase()))

    if (refChanged) {
      // Сначала дроп старый FK (если был)
      if (haveRef) {
        stmts.push(`ALTER TABLE ${table.name} DROP CONSTRAINT IF EXISTS ${haveRef.constraintName!};`)
      }
      // Затем добавить новый (если нужен)
      if (wantRef) {
        const parts = [
          `ALTER TABLE ${table.name} ADD CONSTRAINT ${fkConstraintName(table.name, colName)}`,
          `FOREIGN KEY (${colName}) REFERENCES ${wantRef.table}(${wantRef.column})`
        ]
        if (wantRef.onDelete) parts.push(`ON DELETE ${wantRef.onDelete}`)
        if (wantRef.onUpdate) parts.push(`ON UPDATE ${wantRef.onUpdate}`)
        stmts.push(parts.join(" ") + ";")
      }
    }
  }

  // 3) PRIMARY KEY (сравнение набора колонок)
  const currentPkCols = Object.entries(pgTable)
    .filter(([, c]) => !!c.primaryKey)
    .map(([name]) => name)
    .sort()

  const desiredPkCols = table.primaryKey
    .map(k => {
      const def = table.schema[k] as any
      return typeof def === "string" ? undefined : (def?.key ?? k)
    })
    .filter(Boolean) as string[]

  const pkDiff =
    currentPkCols.length !== desiredPkCols.length ||
    currentPkCols.some((c, i) => c !== desiredPkCols.sort()[i])

  if (pkDiff) {
    // заново переопределяем PK
    stmts.push(`ALTER TABLE ${table.name} DROP CONSTRAINT IF EXISTS ${pkConstraintName(table.name)};`)
    if (desiredPkCols.length > 0) {
      stmts.push(
        `ALTER TABLE ${table.name} ADD CONSTRAINT ${pkConstraintName(table.name)} PRIMARY KEY (${desiredPkCols.join(",")});`
      )
    }
  }

  return stmts.join("\n")
}
